ARG NODE_VERSION=16
ARG SERVER_PORT=5000

FROM node:$NODE_VERSION-buster as base

RUN apt update && apt install -y nodejs && apt install -y npm && apt install -y netcat 

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile && yarn add --dev lerna

COPY . .

RUN chmod +x /app/packages/server/utils/waitForDataBaseConnect/wait-for.sh
RUN yarn lerna bootstrap
RUN rm -rf /app/packages/server/dist/ && yarn build

EXPOSE $SERVER_PORT
