FROM node as builder

RUN apt update && apt install -y nodejs && apt install -y npm

WORKDIR /app

COPY ./packages/client/package.json .
COPY ./packages/client/ .

RUN npm install
RUN npm run build
# RUN rm -rf /app/packages/server/dist/ && yarn build --scope=client


FROM nginx:alpine
WORKDIR /app

COPY --from=builder /app/dist/ /app/
COPY --from=builder /app/nginx.conf /etc/nginx/nginx.conf

EXPOSE $CLIENT_PORT
CMD [ "nginx", "-g", "daemon off;" ]
